[tool.poetry]
name = "email2md"
version = "0.0.1"
description = "Your project description here"
authors = ["DFreireF"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
